# .github/workflows/ci.yml

name: CI Pipeline for QA Project

# Trigger: pornește la push sau pull request pe branch-ul 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  # Primul job: rulează testele
  test:
    runs-on: ubuntu-latest # Rulează pe o mașină virtuală cu Ubuntu
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Acțiune standard pentru a descărca codul

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # O distribuție populară de OpenJDK

      - name: Run tests with Maven
        run: mvn test # Aceeași comandă pe care o rulăm local

  # Al doilea job: construiește și publică imaginea Docker
  build-and-push:
    runs-on: ubuntu-latest
    needs: test # Important: acest job pornește DOAR dacă job-ul 'test' a trecut
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Folosește un secret!
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Folosește un secret!

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/qa-final-project-java:latest